name: Build AudioChain

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install JUCE
      run: |
        # Download and install JUCE
        curl -L "https://github.com/juce-framework/JUCE/releases/download/7.0.9/juce-7.0.9-osx.zip" -o juce.zip
        unzip juce.zip
        sudo mv JUCE /usr/local/JUCE
    
    - name: Configure JUCE module paths
      run: |
        # Update the .jucer file to set correct module paths for CI
        sed -i '' 's|<MODULEPATH id="juce_audio_basics" path=""/>|<MODULEPATH id="juce_audio_basics" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_audio_devices" path=""/>|<MODULEPATH id="juce_audio_devices" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_audio_formats" path=""/>|<MODULEPATH id="juce_audio_formats" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_audio_processors" path=""/>|<MODULEPATH id="juce_audio_processors" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_audio_utils" path=""/>|<MODULEPATH id="juce_audio_utils" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_core" path=""/>|<MODULEPATH id="juce_core" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_data_structures" path=""/>|<MODULEPATH id="juce_data_structures" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_dsp" path=""/>|<MODULEPATH id="juce_dsp" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_events" path=""/>|<MODULEPATH id="juce_events" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_graphics" path=""/>|<MODULEPATH id="juce_graphics" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_gui_basics" path=""/>|<MODULEPATH id="juce_gui_basics" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
        sed -i '' 's|<MODULEPATH id="juce_gui_extra" path=""/>|<MODULEPATH id="juce_gui_extra" path="/usr/local/JUCE/modules"/>|g' AudioChain.jucer
    
    - name: Setup VST2 SDK (if available)
      run: |
        if [ -d "external/VST_SDK_2.4" ]; then
          echo "VST2 SDK submodule detected, setting up headers..."
          VST2_TARGET_DIR="/usr/local/JUCE/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst2.x"
          sudo mkdir -p "$VST2_TARGET_DIR"
          sudo cp -r external/VST_SDK_2.4/pluginterfaces/vst2.x/* "$VST2_TARGET_DIR/" 2>/dev/null || true
          echo "VST2 headers setup complete"
        else
          echo "No VST2 SDK submodule found, skipping VST2 setup"
        fi
    
    - name: Generate Xcode project
      run: |
        /usr/local/JUCE/Projucer.app/Contents/MacOS/Projucer --resave AudioChain.jucer
    
    - name: Build Release
      run: |
        xcodebuild -project Builds/MacOSX/AudioChain.xcodeproj -scheme AudioChain -configuration Release -archivePath AudioChain.xcarchive archive
        xcodebuild -exportArchive -archivePath AudioChain.xcarchive -exportPath AudioChain-Export -exportOptionsPlist <(cat <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>mac-application</string>
            <key>signingStyle</key>
            <string>automatic</string>            
        </dict>
        </plist>
        EOF
        )
    
    - name: Create DMG
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Install create-dmg for creating the DMG
        brew install create-dmg
        
        # Find the built app
        APP_PATH=$(find AudioChain-Export -name "*.app" -type d | head -1)
        
        if [ -n "$APP_PATH" ]; then
          echo "Found app at: $APP_PATH"
          
          # Create DMG
          create-dmg \
            --volname "AudioChain" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "AudioChain.app" 200 190 \
            --hide-extension "AudioChain.app" \
            --app-drop-link 600 185 \
            "AudioChain-macOS.dmg" \
            "$APP_PATH"
        else
          echo "App not found, listing export contents..."
          find AudioChain-Export -type f -name "*.app" || find AudioChain-Export -type d
        fi
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AudioChain-macOS
        path: |
          AudioChain-macOS.dmg
          AudioChain-Export/**/*.app
        if-no-files-found: ignore

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
    
    - name: Install JUCE
      shell: powershell
      run: |
        # Download and install JUCE
        Invoke-WebRequest -Uri "https://github.com/juce-framework/JUCE/releases/download/7.0.9/juce-7.0.9-windows.zip" -OutFile "juce.zip"
        Expand-Archive -Path "juce.zip" -DestinationPath "juce-temp"
        Move-Item -Path "juce-temp\JUCE" -Destination "C:\JUCE"
    
    - name: Configure JUCE module paths
      shell: powershell
      run: |
        # Update the .jucer file to set correct module paths for CI
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_audio_basics" path=""/>', '<MODULEPATH id="juce_audio_basics" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_audio_devices" path=""/>', '<MODULEPATH id="juce_audio_devices" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_audio_formats" path=""/>', '<MODULEPATH id="juce_audio_formats" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_audio_processors" path=""/>', '<MODULEPATH id="juce_audio_processors" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_audio_utils" path=""/>', '<MODULEPATH id="juce_audio_utils" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_core" path=""/>', '<MODULEPATH id="juce_core" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_data_structures" path=""/>', '<MODULEPATH id="juce_data_structures" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_dsp" path=""/>', '<MODULEPATH id="juce_dsp" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_events" path=""/>', '<MODULEPATH id="juce_events" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_graphics" path=""/>', '<MODULEPATH id="juce_graphics" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_gui_basics" path=""/>', '<MODULEPATH id="juce_gui_basics" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
        (Get-Content AudioChain.jucer) -replace '<MODULEPATH id="juce_gui_extra" path=""/>', '<MODULEPATH id="juce_gui_extra" path="C:\JUCE\modules"/>' | Set-Content AudioChain.jucer
    
    - name: Setup VST2 SDK (if available)
      shell: powershell
      run: |
        if (Test-Path "external/VST_SDK_2.4") {
          Write-Host "VST2 SDK submodule detected, setting up headers..."
          $VST2_TARGET_DIR = "C:\JUCE\modules\juce_audio_processors\format_types\VST3_SDK\pluginterfaces\vst2.x"
          New-Item -ItemType Directory -Force -Path $VST2_TARGET_DIR
          Copy-Item -Path "external\VST_SDK_2.4\pluginterfaces\vst2.x\*" -Destination $VST2_TARGET_DIR -Recurse -Force -ErrorAction SilentlyContinue
          Write-Host "VST2 headers setup complete"
        } else {
          Write-Host "No VST2 SDK submodule found, skipping VST2 setup"
        }
    
    - name: Generate Visual Studio project
      shell: cmd
      run: |
        "C:\JUCE\Projucer.exe" --resave AudioChain.jucer
    
    - name: Build Release
      run: |
        msbuild Builds/VisualStudio2022/AudioChain.sln /p:Configuration=Release /p:Platform=x64 /m
    
    - name: Package Windows build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: powershell
      run: |
        # Find the built executable
        $exePath = Get-ChildItem -Path "Builds\VisualStudio2022" -Recurse -Filter "AudioChain.exe" | Where-Object { $_.Directory.Name -eq "Release" } | Select-Object -First 1
        
        if ($exePath) {
          Write-Host "Found executable at: $($exePath.FullName)"
          $releaseDir = $exePath.Directory.FullName
          
          # Create distribution folder
          New-Item -ItemType Directory -Force -Path "AudioChain-Windows-Release"
          Copy-Item -Path "$releaseDir\*" -Destination "AudioChain-Windows-Release" -Recurse -Force
          
          # Create ZIP
          Compress-Archive -Path "AudioChain-Windows-Release\*" -DestinationPath "AudioChain-Windows.zip"
        } else {
          Write-Host "Executable not found, listing build directories..."
          Get-ChildItem -Path "Builds\VisualStudio2022" -Recurse -Include "*.exe" | ForEach-Object { Write-Host $_.FullName }
        }
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AudioChain-Windows
        path: |
          Builds/VisualStudio2022/**/Release/**/*.exe
          AudioChain-Windows.zip
        if-no-files-found: ignore

  release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: AudioChain v${{ github.run_number }}
        body: |
          ## AudioChain Release v${{ github.run_number }}
          
          Cross-platform audio processing application with VST plugin chain support.
          
          ### Downloads
          - **macOS**: AudioChain-macOS.dmg
          - **Windows**: AudioChain-Windows.zip
          
          ### Features
          - Real-time audio processing through VST plugin chains
          - Support for VST2, VST3, and Audio Unit (macOS) plugins
          - Cross-platform compatibility (macOS and Windows)
          - Modern JUCE-based GUI
          
          Built from commit: ${{ github.sha }}
        files: |
          AudioChain-macOS/AudioChain-macOS.dmg
          AudioChain-Windows/AudioChain-Windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 